### ISSUE TITLE
Why not use “align-self:flex-start” instead of “top”？

### ISSUE THREAD

**Issue by E-Dictionary** [StefanKovac/flex-layout-attribute#10]
"margin-bottom: auto" had no effect in some browsers

**Comment by StefanKovac** [comment]
1. FLA is designed to use common alignment keywords regardless of flex direction. Result of “align-self:flex-start;” depends on flex direction while with "top" you always get the same result - top alignment. 
2. Be specific please. 

Thanks.

**Comment by E-Dictionary** [comment]
thank you.
I now know this is your design intent.
"self=‘top’" On my phone's browser no effect. My phone system is android6.0, the model is Huawei mate8.

**Comment by StefanKovac** [comment]
Make sure item height is not the same as container height, otherwise you wont notice top alignment.   Basically, I'm shooting in the dark here so feel free to post url so I can take a look.
