### ISSUE TITLE
[question] Bower or Npm?

### ISSUE THREAD

**Issue by renatodeleao** [StefanKovac/flex-layout-attribute#11]
This is **awesome**.

Like really awesome.

I first saw a sort of this technique while inspecting [Material Design Icons Page](https://design.google.com/icons/), since then I've always have a file [like this](https://gist.github.com/renatodeleao/d844cd35cce9108f2ff7750bb6a1eec2) to quick prototype for clients
### But this is hole other level! 💥

Are you considering support package managers?  
## Thanks.

![Code](https://dl.dropboxusercontent.com/u/14116976/Screenshot%202016-08-05%2012.30.40.png)

**Comment by StefanKovac** [comment]
Yeah, that's pretty much the same technique. 

NPM: 
`npm i flex-layout-attribute`

Still considering bower though, but you can:
`bower install git://github.com/StefanKovac/flex-layout-attribute.git`

Thanks Renato!

**Comment by renatodeleao** [comment]
That's all I need to hear.

Thanks! 
Keep shipping! :shipit:

**Comment by lukasoppermann** [comment]
Hey @StefanKovac, using `bower install git://github.com/StefanKovac/flex-layout-attribute.git` do I get all new versions on `bower update`?

**Comment by StefanKovac** [comment]
Hi

**Comment by StefanKovac** [comment]
Hi @lukasoppermann, I think not but don't take me for granted. 

As far I understand, `bower update` needs `bower.json` to compare versions in order to update package  and since there is no such file within FLA, no updates will occur. Any experienced bower user here to confirm this? 

Thanks.

**Comment by lukasoppermann** [comment]
In this case could you please add it to bower? There are still many people (including myself) who use bower for front-end stuff.

I only use npm for my gulp stuff, as I am using php, so bower with adding components to bower_components is a very good separation for me. 

**Plus** it should only me a couple minutes of your time to add bower. 😄
