### ISSUE TITLE
Choose width of main container

### ISSUE THREAD

**Issue by fluxxus** [StefanKovac/flex-layout-attribute#13]
Maybe I am missing something obvious (it is probably intentionaly left out), but I believe it would be a good addition.

I would like to choose different widths for the main flex container, along with the option to have it horizontally centered.

The way it is now, it always defaults to 100%(then again, maybe I am missing something). It would be nice to have an option to choose let's say 70% width and center it. Also, maybe to use the already predefined widths for `sm-, md- and lg-`.

p.s. Almost forgot to add. Thanks for the great library, I am using this in production on two sites I am working on now !

**Comment by StefanKovac** [comment]
Please check sizing options, particulary [predefined widths in pixels](http://progressivered.com/fla/?d=0&v=1&h=1&s=0&i=000&a=000#self-size) for defining element size in pixels. Example for centered container with 720px width:
`<div layout="column" self="center size-large">`
`your content here...`
`</div>`

Hvala i pozdrav ;)

**Comment by fluxxus** [comment]
Znao sam da sam nešto promašio! Hvala :)
