### ISSUE TITLE
Edge performance problems

### ISSUE THREAD

**Issue by fxlrnrpt** [StefanKovac/flex-layout-attribute#17]
Hi Stefan! 
There's a known performance problems for rendering attribute rules by Edge. A dedicated research (here)[https://medium.com/@andreygoncharov/edge-hates-you-attributes-d15faf162939]. Would you consider moving to classes in the next major version?

**Comment by fxlrnrpt** [comment]
Sorry for the broken link “Edge hates you attributes” https://medium.com/@andreygoncharov/edge-hates-you-attributes-d15faf162939

**Comment by StefanKovac** [comment]
Hi @keenondrums and thanks for your suggestion!

I understand your concerns though I'm more into considering FLA in real world use case scenarios.  FLA is designed as a quick prototyping and applying tens of thousands attributes in one page is not a good to build anything except benchmark performance tests.
