### ISSUE TITLE
What about W3C Validation?

### ISSUE THREAD

**Issue by emitremmus** [StefanKovac/flex-layout-attribute#2]
Hello,
your idea, working with additional syntax in div element, is very good. But what about the W3C Validation.
I tried it on my own and W3C gives me the following Error: "Error: Attribute **layout** not allowed on element div at this point."

**Comment by mr-moon** [comment]
It can be possibly fixed by prefixing `layout` with `data-` prefix, then it'll validate. However, it looks very minor to me.

**Comment by StefanKovac** [comment]
@emitremmus basically what @mr-moon said. You can build custom version of FLA (from sass files provided) based on attribute names you like — [set this variables](https://github.com/StefanKovac/flex-layout-attribute/blob/master/sass/flex-layout-attribute/_vars.scss). e.g. $LAYOUT : "data-layout";

Hope that helps. Thanks.

**Comment by nltncsr** [comment]
That can be added on a major version, like in `2.0.0`, as well as supports to others CSS preprocessors.

**Comment by KittyGiraudel** [comment]
Agreed, it should be `data-layout`. This is why data-attributes were introduced in the first place.

**Comment by StefanKovac** [comment]
Besides clarity, I like unprefixed layout attribute for what it represents  — a non-standard attribute for non-standard way of dealing with flexbox layout. 

Personally, I don't see real benefits of using `data-` prefix beside W3C compliance, which I frankly find irrelevant in this case. However, I'm leaving this issue open (for a while) in case I'm missing something.

Thanks @cesarasaservice @HugoGiraudel

**Comment by aziz** [comment]
It can not be used out of the box with React.js since it's removing layout attribute. Changing it to `data-layout` will fix this issue.

**Comment by StefanKovac** [comment]
Hey @aziz that's interesting. I've never used React but did you tried http://stackoverflow.com/questions/31273093/how-to-add-custom-html-attributes-in-jsx or http://stackoverflow.com/a/33860892/6392049 ?

**Comment by aziz** [comment]
@StefanKovac all those methods you linked above are frowned upon and not recommended in our team. 
I still think adding a little `data-` and making it future proof is a much better and more reliable choice.

**Comment by aziz** [comment]
@StefanKovac could you publish the `scss` source along with the `css` to the `npm` so that we can use the scss version to do out customization rather than hard copying it from your repo.

**Comment by StefanKovac** [comment]
@aziz apparently `npm` package name is taken !? Someone already created it with only `css` files. Now, should I contact the author to transfer ownership or create scoped package?

**Comment by aziz** [comment]
He should be willing to hand it over for sure. So, first contact the author.

**Comment by StefanKovac** [comment]
FLA is now on npm: https://www.npmjs.com/package/flex-layout-attribute

@thinkholic I appreciate your understanding. Thanks.

**Comment by danielkrich** [comment]
@aziz , did you find a solution for your react app? Isn't working for me either...
