### ISSUE TITLE
Browser Support??

### ISSUE THREAD

**Issue by james-brndwgn** [StefanKovac/flex-layout-attribute#3]
What browsers has this been tested on? Perhaps future versions could have flexibilty integration?

**Comment by StefanKovac** [comment]
@james-brndwgn  Browser support for FLA is the same as for [flexbox](http://caniuse.com/#feat=flexbox) — FLA is built with autoprefixer set to 'last 2 version'.

I don't understand second question.

**Comment by james-brndwgn** [comment]
Thank you, good to know about autoprefixer. This is what I meant by Flexibility: https://github.com/10up/flexibility - But if browser support is last 2 versions then it won't apply. Thanks for your response.

**Comment by StefanKovac** [comment]
Oh, I didn't know about that polyfill. You can try adding their respective declarations to FLA css if you want to try.

About polyfill — It looks like too much effort to support flexbox for older IE. If you really have to support those browser I would suggest you to stay away from flexbox completely, create separated/dedicated  CSS (for layout use floats or table) and conditionally load them for this browsers only.  

Thanks @james-brndwgn
