### ISSUE TITLE
Attribute selector performance over class selectors

### ISSUE THREAD

**Issue by 7ammer** [StefanKovac/flex-layout-attribute#6]
I really like the concept of this library! Traditionally though attribute selectors have been known to be a lot slower than classes as they are universal selectors. I'm curious, have you done any performance tests to see if there is a big difference?

**Comment by StefanKovac** [comment]
@7immy I haven't done any performance test, but you are right, universal selectors are slower than class selectors. However, nowdays browsers are really good at CSS parsing and you are unlikely to notice any difference in speed if you dealing with regular web projects. I guess some speed differences may be noticeable in test environments when you are dealing with tens of thousands of selectors at once.

Do you know any reliable way of testing CSS selector performance?
