### ISSUE TITLE
Bower package

### ISSUE THREAD

**Issue by selfagency** [StefanKovac/flex-layout-attribute#7]
I see you're on npm but could you please [make a Bower package](http://bower.io/docs/creating-packages/) too?

Thanks

**Comment by StefanKovac** [comment]
Hi @selfagency, 
thanks for the proposal. 

You can install FLA with bower:
`bower install git://github.com/StefanKovac/flex-layout-attribute.git`

I not sure if adding bower package is worthwhile but let's wait for while and see if there will be more request. 

Thanks!
