### ISSUE TITLE
The latest version problem on npm

### ISSUE THREAD

**Issue by nolsherry** [StefanKovac/flex-layout-attribute#8]
Hello @StefanKovac,
I am the member of [cdnjs](https://github.com/cdnjs) project.
We want to host this library.
I downloaded the latest version v1.0.2, but I found the version description of files such as `flex-layout-attribute.min.css`, `flex-layout-attribute.css`  which downloaded from npm were wrong, and the version description is still v1.0.1. Could you update the latest version description on npm?
Thanks very much!

cdnjs/cdnjs#8174

**Comment by StefanKovac** [comment]
Hi @nolsherry, 
ahh, thanks for letting me know. 
I've bumped version to 1.0.3 on npm & here on github — hopefully it will work for you now. Please let know.
Thank you!

**Comment by nolsherry** [comment]
Hi @StefanKovac,
thanks for your help, and it works for me, thank you very much!
