### ISSUE TITLE
Browser support?

### ISSUE THREAD

**Issue by pwFoo** [StefanKovac/flex-layout-attribute#9]
Hi, looks great! Thank you for sharing our work here :)

I see the `display: -ms-flexbox;`, but it seems not work with ie10.
Tested your demo with chrome, ff,  ie11, edge and older ie versions (ietester).

Modern browser work fine!
But would ie10 support (old syntax) possible? ie 8 / 9 could be optional done with flexibility maybe...

You should add some (cross) browser support information to the readme file. ;)

**Comment by StefanKovac** [comment]
Thanks @pwFoo 

Yep, FLA is built for modern browsers, I will add that note in readme file.
Old browser support has already been discussed [here](https://github.com/StefanKovac/flex-layout-attribute/issues/3). You can always built your own custom FLA version but I'm not recommending using flexbox for old IE at all.

**Comment by pwFoo** [comment]
So FLA supports just modern browsers like my own simple css "framework" / file, but with additional nice html attribute support! :)

I'll take a closer look at your css file and maybe move from my custom file to FLA or will combine it...

IE8-10 could be supported with some dirty JavaScript (maybe something like https://github.com/adamwulf/Columnizer-jQuery-Plugin) which works with IE to build columns...

Information about cross browser support should be added to the readme file.

Thanks!
